export const LANG = {
  en: {
    welcome: "Welcome, {name}!",
    ready: "Ready to take on {title}",
    initializing: "Initializing...",
    startedTest: "Started Test...",
    notFoundTitle: "Neural Interface Not Found",
    returnToHub: "Return to Hub",
    submitQuiz: "Submit Quiz",
    submitQuizQuestion: "Are you sure you want to submit your quiz? This action cannot be undone.",
    submitQuizAllAnswered: "You have answered all questions. Are you ready to submit your quiz?",
    continueQuiz: "Continue Quiz",
    reviewAnswers: "Review Answers",
    submitNow: "Submit Now",
    timeExpired: "Time Expired!",
    timeExpiredMsg: "Your quiz time has expired. Your answers will be automatically submitted.",
    warningCritical: "⚠️ CRITICAL:",
    timeDepleting: "Time quantum depleting rapidly!",
    clearResponse: "Clear Response",
    markForReview: "Mark for Review",
    previous: "Previous",
    next: "Next",
    completed: "Completed",
    incomplete: "Incomplete",
    unvisited: "Unvisited",
    reviewQueue: "Review Queue",
    statusQuestions: "Status Questions",
    active: "Active",
    neuralQuery: "Neural Query",
    currentQuestions: "Current Questions",
    completedLabel: "Completed",
    timeQuantum: "Time Quantum",
    answeredOf: "{answered}/{total}",
    currentOf: "{current}/{total}",
    loadingAnswerKeys: "Loading answer keys...",
    loading: "Loading...",
    notPostedResults: "Not Posted the results",
    submitSuccess: "Quiz submitted successfully!",
    submitFail: "Failed to submit quiz",
    loadQuizFail: "Failed to load quiz",
    missingQuiz: "Quiz data is missing. Please reload the page.",
    userNotFound: "User not found. Please register again.",
    warningIncomplete: "Warning: Incomplete Questions",
    unansweredWarning: "You have {count} unanswered questions. These will be marked as incorrect if you proceed.",
  },
  hi: {
    welcome: "स्वागत है, {name}!",
    ready: "{title} के लिए तैयार हैं",
    initializing: "प्रारंभ हो रहा है...",
    startedTest: "परीक्षा शुरू हो गई...",
    notFoundTitle: "न्यूरल इंटरफ़ेस नहीं मिला",
    returnToHub: "मुख्य पृष्ठ पर लौटें",
    submitQuiz: "क्विज़ सबमिट करें",
    submitQuizQuestion: "क्या आप वाकई अपना क्विज़ सबमिट करना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।",
    submitQuizAllAnswered: "आपने सभी प्रश्नों के उत्तर दे दिए हैं। क्या आप क्विज़ सबमिट करने के लिए तैयार हैं?",
    continueQuiz: "क्विज़ जारी रखें",
    reviewAnswers: "उत्तर देखें",
    submitNow: "अभी सबमिट करें",
    timeExpired: "समय समाप्त!",
    timeExpiredMsg: "आपका क्विज़ समय समाप्त हो गया है। आपके उत्तर स्वचालित रूप से सबमिट कर दिए जाएंगे।",
    warningCritical: "⚠️ चेतावनी:",
    timeDepleting: "समय तेजी से समाप्त हो रहा है!",
    clearResponse: "उत्तर हटाएँ",
    markForReview: "समीक्षा के लिए चिह्नित करें",
    previous: "पिछला",
    next: "अगला",
    completed: "पूर्ण",
    incomplete: "अपूर्ण",
    unvisited: "अदेखा",
    reviewQueue: "समीक्षा कतार",
    statusQuestions: "प्रश्नों की स्थिति",
    active: "सक्रिय",
    neuralQuery: "न्यूरल प्रश्न",
    currentQuestions: "वर्तमान प्रश्न",
    completedLabel: "पूर्ण",
    timeQuantum: "समय",
    answeredOf: "{answered}/{total}",
    currentOf: "{current}/{total}",
    loadingAnswerKeys: "उत्तर कुंजी लोड हो रही है...",
    loading: "लोड हो रहा है...",
    notPostedResults: "परिणाम पोस्ट नहीं किए गए हैं",
    submitSuccess: "क्विज़ सफलतापूर्वक सबमिट हो गया!",
    submitFail: "क्विज़ सबमिट करने में विफल",
    loadQuizFail: "क्विज़ लोड करने में विफल",
    missingQuiz: "क्विज़ डेटा गायब है। कृपया पृष्ठ को पुनः लोड करें।",
    userNotFound: "उपयोगकर्ता नहीं मिला। कृपया फिर से पंजीकरण करें।",
    warningIncomplete: "चेतावनी: अपूर्ण प्रश्न",
    unansweredWarning: "आपके {count} प्रश्न अनुत्तरित हैं। यदि आप आगे बढ़ते हैं तो इन्हें गलत माना जाएगा।",
  }
}; 